name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    types: closed
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_DEFAULT_REGION=${{secrets.AWS_REGION}}
      - name: Login AWS ECR
        run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_REPOSITORY_URI}}
      - name: Build and publish image
        run: |
          docker build -t ${{secrets.IMAGE_NAME}} .
          docker tag ${{secrets.IMAGE_NAME}}:latest
          ${{secrets.ECR_REPOSITORY_URI}}/${{secrets.IMAGE_NAME}}:latest
          docker push ${{secrets.ECR_REPOSITORY_URI}}/${{secrets.IMAGE_NAME}}:latest